name = "himahlini"
pages_build_output_dir = "dist/client"

[vars]
GITHUB_DEPLOY_OWNER = "himahlini"
GITHUB_DEPLOY_REPO = "landing-page"
GITHUB_DEPLOY_WORKFLOW = "deploy.yml"
GITHUB_DEPLOY_REF = "main"
R2_BUCKET_NAME = "himahlini-assets"

[[d1_databases]]
binding = "DB"
database_name = "himahlini-cms"
database_id = "052f2f32-1726-4987-8814-33f275060b58"

[[r2_buckets]]
binding = "CMS_ASSETS"
bucket_name = "himahlini-assets"
